Repository boostcampwm-2021/iOS01-Booster, pull requests merged in 2021-12, with the labels that each got.

#221 [공통] 레이아웃, 애니메이션 추가
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Extensions/UIButton+Extension.swift
  Booster/Booster/Extensions/UIImage+Extension.swift
  Booster/Booster/Extensions/UIView+Extension.swift
  Booster/Booster/Repositories/CoreData/CoreDataKeys.swift
  Booster/Booster/Resources/Assets.xcassets/camera.imageset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/camera.imageset/camera.pdf
  Booster/Booster/Resources/Assets.xcassets/cameraFill.imageset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/cameraFill.imageset/cameraFill.pdf
  Booster/Booster/Resources/Assets.xcassets/check.imageset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/check.imageset/check.pdf
  Booster/Booster/Resources/Assets.xcassets/save.imageset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/save.imageset/save.pdf
  Booster/Booster/Storyboards/User.storyboard
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/Usecases/EnrollUsecase.swift
  Booster/Booster/Usecases/ModifyFeedUsecase.swift
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/Usecases/UserUsecase.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewControllers/User/RemoveAllDataViewController.swift
  Booster/Booster/ViewModels/User/NotificationSettingViewModel.swift
  Booster/Booster/Views/Tracking/TrackingInfoView.swift
  Booster/Booster/Views/Utils/ToastView.swift
Labels: 🔮리뷰, 🧿UI, 🔧Refactor

#222 [공통] Usecase 공통화 작업
  Booster/Booster/Usecases/BoosterTabBarUsecase.swift
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/Usecases/ModifyFeedUsecase.swift
  Booster/Booster/ViewControllers/BaseProtocol/BoosterTabBarViewController.swift
  Booster/Booster/ViewControllers/Feed/FeedViewController.swift
  Booster/Booster/ViewModels/Base/BoosterTabBarViewModel.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/ViewModels/Feed/FeedViewModel.swift
  Booster/Booster/ViewModels/Feed/ModifyFeedViewModel.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
Labels: 🔮리뷰, 🔧Refactor

#224 [hotFix] 불필요한 파일 및 디렉토리 삭제
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Extensions/BoosterObservable.swift
  Booster/Booster/Views/Renderers/CircleRenderer.swift
Labels: 💥버그

#225 [공통] core data, healthKit -> removeAll 사항들 모두 single로 변경
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/AppDelegates/AppDelegate.swift
  Booster/Booster/Repositories/CoreDataManager.swift
  Booster/Booster/Services/HealthKitManager.swift
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/Usecases/EnrollUsecase.swift
  Booster/Booster/Usecases/FeedUseCase.swift
  Booster/Booster/Usecases/HomeUsecase.swift
  Booster/Booster/Usecases/ModifyFeedUsecase.swift
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/Usecases/UserUsecase.swift
  Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
  Booster/Booster/ViewControllers/User/RemoveAllDataViewController.swift
  Booster/Booster/ViewModels/Enroll/EnrollViewModel.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/ViewModels/Feed/FeedViewModel.swift
  Booster/Booster/ViewModels/Feed/ModifyFeedViewModel.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
  Booster/Booster/ViewModels/User/UserViewModel.swift
  Booster/FeedTests/DetailFeedViewModelTests.swift
  Booster/UserTests/UserViewModelTests.swift
Labels: 🔮리뷰, 🔧Refactor

#226 [fix] 홈 버그 수정
  Booster/Booster/AppDelegates/AppDelegate.swift
  Booster/Booster/ViewControllers/Home/HomeViewController.swift
  Booster/Booster/ViewModels/Home/HomeViewModel.swift
Labels: 💥버그, 🔍수정
