Repository boostcampwm-2021/iOS01-Booster, pull requests merged in 2021-11, with the labels that each got.

#12 [B-31] 마일스톤 포토 마커 표시
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Enums/TrackingState.swift
  Booster/Booster/Extensions/UIAlertController+Extention.swift
  Booster/Booster/Models/Coordinate.swift
  Booster/Booster/Models/MileStone.swift
  Booster/Booster/Models/TrackingModel.swift
  Booster/Booster/Models/User.swift
  Booster/Booster/Storyboards/Tracking/Tracking.storyboard
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewControllers/Tracking/View/PhotoAnnotationView.swift
  Booster/Booster/ViewControllers/Tracking/View/PhotoAnnotationView.xib
  Booster/Booster/ViewControllers/Tracking/View/TrackingMapView.swift
  Booster/Booster/ViewModels/TrackingProgressViewModel.swift
Labels: feature

#18 [B-Refactor] milestone을 bind로 수정
  Booster/Booster/Models/TrackingModel.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewControllers/Tracking/View/TrackingMapView.swift
  Booster/Booster/ViewModels/TrackingProgressViewModel.swift
Labels: Fix

#21 [Feature/home] 홈페이지 및 피드 화면 UI 구성 & HealthKit 구성
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Booster.entitlements
  Booster/Booster/Extensions/FeedTableViewCell.swift
  Booster/Booster/Extensions/FeedViewModel.swift
  Booster/Booster/Extensions/HomeData.swift
  Booster/Booster/Extensions/TimeInterval+extension.swift
  Booster/Booster/Extensions/TrackingRecord.swift
  Booster/Booster/Resources/Assets.xcassets/foot.imageset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/foot.imageset/foot.pdf
  Booster/Booster/Resources/HomeViewModel.swift
  Booster/Booster/Resources/Info.plist
  Booster/Booster/Storyboards/Feed.storyboard
  Booster/Booster/Storyboards/Home.storyboard
  Booster/Booster/ViewControllers/FeedViewController.swift
  Booster/Booster/ViewControllers/HomeViewController.swift
  Booster/Podfile.lock
Labels: feature

#22 [Feature/statistics] 통계 화면 구성
  Booster/BarChartView.swift
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Booster.entitlements
  Booster/Booster/Storyboards/Analysis.storyboard
  Booster/Booster/Storyboards/Base.lproj/Main.storyboard
  Booster/Booster/Storyboards/Statistics.storyboard
  Booster/Booster/ViewControllers/AnalysisViewController.swift
  Booster/Booster/ViewControllers/Observable.swift
  Booster/Booster/ViewControllers/Statistics.swift
  Booster/Booster/ViewControllers/StatisticsViewController.swift
  Booster/Booster/ViewControllers/StatisticsViewModel.swift
  Booster/Button.swift
  Booster/HealthStoreManager.swift
Labels: review, feature

#20 [B-트래킹 시작 화면, 트래킹 진행 화면, 마일스톤 촬영 화면, 활동 기록 화면] 2주차 코드
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Booster.entitlements
  Booster/Booster/Extensions/NSAttributedString.swift
  Booster/Booster/Extensions/Observable.swift
  Booster/Booster/Extensions/UIAlertController+Extention.swift
  Booster/Booster/Extensions/UIFont.swift
  Booster/Booster/Models/Coordinate.swift
  Booster/Booster/Models/MileStone.swift
  Booster/Booster/Models/TrackingModel.swift
  Booster/Booster/Models/UserInfo.swift
  Booster/Booster/Renderers/CircleRenderer.swift
  Booster/Booster/Repositories/CoreData/Booster.xcdatamodeld/Booster.xcdatamodel/contents
  Booster/Booster/Repositories/RepositoryManager.swift
  Booster/Booster/Resources/Info.plist
  Booster/Booster/Storyboards/Base.lproj/Main.storyboard
  Booster/Booster/Storyboards/Tracking.storyboard
  Booster/Booster/Storyboards/Tracking/Tracking.storyboard
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/ViewControllers/HomeViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingViewController.swift
  Booster/Booster/ViewControllers/Tracking/View/CountdownView.swift
  Booster/Booster/ViewControllers/Tracking/View/PhotoAnnotationView.swift
  Booster/Booster/ViewControllers/Tracking/View/PhotoAnnotationView.xib
  Booster/Booster/ViewControllers/Tracking/View/TrackingMapView.swift
  Booster/Booster/ViewControllers/TrackingViewController.swift
  Booster/Booster/ViewModels/TrackingProgressViewModel.swift
  Booster/Tracking+CoreDataClass.swift
  Booster/Tracking+CoreDataProperties.swift
  Booster/User+CoreDataClass.swift
  Booster/User+CoreDataProperties.swift
  README.md
Labels: review, feature

#28 refac: healthkit, home 수정 및 AppIcon
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x-1.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x-1.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x-1.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  Booster/Booster/Resources/Assets.xcassets/AppIcon.appiconset/ItunesArtwork@2x.png
  Booster/Booster/Resources/Assets.xcassets/BoosterColorSet/boosterBackground.colorset/Contents.json
  Booster/Booster/Services/HealthStoreManager.swift
  Booster/Booster/Storyboards/Base.lproj/Main.storyboard
  Booster/Booster/Storyboards/Feed.storyboard
  Booster/Booster/Storyboards/Home.storyboard
  Booster/Booster/ViewControllers/HomeViewController.swift
  Booster/Booster/ViewModels/HomeViewModel.swift
Labels: 🔧Refactor

#41 [#31, #33, #34, #35] 포토 마커 화면 구현 완료
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Models/Coordinate.swift
  Booster/Booster/Models/MileStone.swift
  Booster/Booster/ViewControllers/MileStonePhotoViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/MileStonePhotoViewModel.swift
  Booster/Booster/ViewModels/TrackingProgressViewModel.swift
  Booster/Booster/Views/PhotoAnnotationView.swift
  Booster/Booster/Views/PhotoAnnotationView.xib
  Booster/Booster/Views/TrackingMapView.swift
Labels: 🔮리뷰, 🔥Feature, ✨리뷰완료, 🧿UI, 🐸Architecture

#47 [#42, #44] 기능 구현 완료
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Extensions/UIImage+Extension.swift
  Booster/Booster/Extensions/UIResponder+Extension.swift
  Booster/Booster/Storyboards/Feed.storyboard
  Booster/Booster/ViewControllers/DetailFeedViewController.swift
  Booster/Booster/ViewControllers/FeedViewController.swift
  Booster/Booster/ViewModels/DetailFeedViewModel.swift
Labels: 🔮리뷰, 🔥Feature, 🧿UI

#49 [B-31] 마일스톤 마커 표시 버그 Fix #48
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Extensions/UIImage+Extension.swift
  Booster/Booster/Storyboards/Tracking.storyboard
  Booster/Booster/ViewControllers/MileStonePhotoViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/TrackingProgressViewModel.swift
  Booster/Booster/Views/Components/Components.swift
  Booster/Booster/Views/TrackingMapView.swift
Labels: 💥버그, 🔮리뷰, 🔍수정

#53 [B-24] 카운트 후 화면 전환 + Core Data Entity 수정
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Models/TrackingModel.swift
  Booster/Booster/Repositories/CoreData/Tracking+CoreDataClass.swift
  Booster/Booster/Resources/Booster.xcdatamodeld/Booster.xcdatamodel/contents
  Booster/Booster/Storyboards/Tracking.storyboard
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingViewController.swift
  Booster/Booster/Views/CountdownView.swift
  Booster/Booster/Views/TrackingCountDownView.swift
  Booster/Tracking+CoreDataClass.swift
  Booster/Tracking+CoreDataProperties.swift
Labels: 🔮리뷰, 🔥Feature

#55 [D-63] 이동 경로를 나타낸다
  Booster/Booster/ViewControllers/MileStonePhotoViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/TrackingProgressViewModel.swift
  Booster/Booster/Views/TrackingMapView.swift
Labels: 🔥Feature

#56 [C-52, 53] 막대 그래프 보여주기
  Booster/Booster/Models/Statistics.swift
  Booster/Booster/Views/BarAxisChartView.swift
  Booster/Booster/Views/BarAxisChartView.xib
  Booster/Booster/Views/BarSelectionAxisChartView.swift
  Booster/Booster/Views/BarSelectionAxisChartView.xib
  Booster/Booster/Views/Chart.swift
  Booster/Booster/Views/ChartView.swift
  Booster/Booster/Views/ChartView.xib
Labels: 🔮리뷰, 🔧Refactor

#57 [B] 트래킹 기능 구현 1차 완료
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Extensions/UIAlertController+Extention.swift
  Booster/Booster/Extensions/UIColor+Extension.swift
  Booster/Booster/Extensions/UIImage+Extension.swift
  Booster/Booster/Models/Coordinate.swift
  Booster/Booster/Models/MileStone.swift
  Booster/Booster/Models/TrackingModel.swift
  Booster/Booster/Repositories/CoreData/Tracking+CoreDataClass.swift
  Booster/Booster/Repositories/RepositoryManager.swift
  Booster/Booster/Resources/Booster.xcdatamodeld/Booster.xcdatamodel/contents
  Booster/Booster/Services/HealthStoreManager.swift
  Booster/Booster/Storyboards/Tracking.storyboard
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/ViewControllers/MileStonePhotoViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingViewController.swift
  Booster/Booster/ViewModels/MileStonePhotoViewModel.swift
  Booster/Booster/ViewModels/TrackingProgressViewModel.swift
  Booster/Booster/Views/Components/Components.swift
  Booster/Booster/Views/CountdownView.swift
  Booster/Booster/Views/PhotoAnnotationView.swift
  Booster/Booster/Views/PhotoAnnotationView.xib
  Booster/Booster/Views/TrackingCountDownView.swift
  Booster/Booster/Views/TrackingMapView.swift
  Booster/Tracking+CoreDataClass.swift
  Booster/Tracking+CoreDataProperties.swift
Labels: 💥버그, 🔮리뷰, 🔥Feature, 🔍수정

#60 [#59] 코드 리팩토링
  Booster/Booster/Models/Coordinate.swift
  Booster/Booster/ViewControllers/MileStone/MileStonePhotoViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
  Booster/Booster/Views/Tracking/PhotoAnnotationView.swift
  Booster/Booster/Views/Tracking/TrackingMapView.swift
Labels: 🔮리뷰, 🔧Refactor

#62 [refactor] 코드컨벤션 & minor 수정
  Booster/Booster/Extensions/UIImage+Extension.swift
  Booster/Booster/Models/HomeData.swift
  Booster/Booster/Storyboards/Feed.storyboard
  Booster/Booster/Storyboards/Home.storyboard
  Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
  Booster/Booster/ViewControllers/Feed/FeedViewController.swift
  Booster/Booster/ViewControllers/Home/HomeViewController.swift
  Booster/Booster/ViewModels/Feed/FeedViewModel.swift
  Booster/Booster/ViewModels/Home/HomeViewModel.swift
  Booster/Booster/Views/EmptyView.swift
  Booster/Booster/Views/Feed/FeedTableViewCell.swift
Labels: 🔮리뷰, 🔧Refactor

#66 [D-63] 이동 경로를 나타낸다
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
  Booster/Booster/Views/Tracking/TrackingMapView.swift
Labels: 🔮리뷰, 🔥Feature, 🔍수정, 🧿UI

#68 [B-45] 이동 경로에 gradient 색 입히기 - close #67
  Booster/Booster/Extensions/UIColor+Extension.swift
  Booster/Booster/Views/Tracking/TrackingMapView.swift
Labels: 🔮리뷰, 🧿UI

#70 [D] 피드 리스트 empty view 보여주기 및 feed detail 간 데이터 전달
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Models/Coordinate.swift
  Booster/Booster/Models/TrackingRecord.swift
  Booster/Booster/Repositories/RepositoryManager.swift
  Booster/Booster/Resources/Booster.xcdatamodeld/Booster.xcdatamodel/contents
  Booster/Booster/Storyboards/Feed.storyboard
  Booster/Booster/Usecases/FeedUseCase.swift
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
  Booster/Booster/ViewControllers/Feed/FeedViewController.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/ViewModels/Feed/FeedViewModel.swift
  Booster/Booster/Views/Feed/FeedCell.swift
  Booster/Tracking+CoreDataClass.swift
  Booster/Tracking+CoreDataProperties.swift
Labels: 🔮리뷰, 🔥Feature

#71 [C-52 ~ 57] 막대차트뷰 리팩토링
  .github/ISSUE_TEMPLATE/--------------.md
  .github/ISSUE_TEMPLATE/------.md
  .github/ISSUE_TEMPLATE/-----.md
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Models/Button.swift
  Booster/Booster/Models/Statistics.swift
  Booster/Booster/Storyboards/Statistics.storyboard
  Booster/Booster/ViewControllers/Statistic/StatisticsViewController.swift
  Booster/Booster/ViewModels/Statistic/StatisticsViewModel.swift
  Booster/Booster/Views/Chart.swift
  Booster/Booster/Views/Statistic/BarChartView.swift
  Booster/Booster/Views/Statistic/ChartView.swift
  Booster/StatisticsTests/StatisticsModelTests.swift
  Booster/StatisticsTests/StatisticsViewModelTests.swift
  PULL_REQUEST_TEMPLATE.md
Labels: 🔮리뷰, 🔥Feature, 🧿UI, 💣Test, 🔧Refactor

#72 [D] 활동 상세 화면 CoreData 연결 및 MapKit
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Extensions/UIImage+Extension.swift
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
  Booster/Booster/ViewControllers/Feed/FeedViewController.swift
  Booster/Booster/ViewControllers/Home/HomeViewController.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/ViewModels/Home/HomeViewModel.swift
  Booster/Booster/Views/EmptyView.swift
Labels: 🔮리뷰, 🔥Feature, 🐸Architecture

#86 [refactor] 뷰 레이아웃 & 컬러 수정
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Extensions/UIColor+Extension.swift
  Booster/Booster/Models/HomeModel.swift
  Booster/Booster/Resources/Assets.xcassets/BoosterColorSet/boosterBlackLabel.colorset/Contents.json
  Booster/Booster/Storyboards/Home.storyboard
  Booster/Booster/Storyboards/Statistics.storyboard
  Booster/Booster/Storyboards/Tracking.storyboard
  Booster/Booster/Usecases/HomeUsecase.swift
  Booster/Booster/ViewControllers/Home/HomeViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/Home/HomeViewModel.swift
  Booster/Booster/Views/Tracking/TrackingCountDownView.swift
Labels: 🔮리뷰, 🧿UI, 🔧Refactor

#76 [#75 #77 #78 #79 #80 #81 #84 #85] 피드 & 트래킹 부분 수정
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Models/Coordinate.swift
  Booster/Booster/Models/FeedList.swift
  Booster/Booster/Models/MileStone.swift
  Booster/Booster/Models/UserInfo.swift
  Booster/Booster/Repositories/RepositoryManager.swift
  Booster/Booster/Services/HealthStoreManager.swift
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/Usecases/FeedUseCase.swift
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/ViewControllers/Feed/FeedViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/ViewModels/Feed/FeedViewModel.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
  Booster/Booster/Views/Feed/FeedCell.swift
  Booster/Booster/Views/Tracking/TrackingCountDownView.swift
  Booster/StatisticsTests/StatisticsModelTests.swift
  Booster/TrackingProgressTests/TrackingProgressTests.swift
Labels: 🔮리뷰, 🔥Feature, 🔍수정, 💣Test, 🐸Architecture

#112 [D] 피드 리스트 불러오기 오류
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Booster.entitlements
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/Feed/FeedViewModel.swift
Labels: 💥버그, 🔮리뷰, 🔍수정

#114 [C] Rx + Usecase 리팩토링 및 버그 수정
  Booster/Booster/Models/StepStatitstics.swift
  Booster/Booster/Storyboards/Statistics.storyboard
  Booster/Booster/Usecases/StatisticsUsecase.swift
  Booster/Booster/ViewControllers/Statistic/StatisticsViewController.swift
  Booster/Booster/ViewModels/Statistic/StatisticsViewModel.swift
  Booster/Booster/Views/Statistic/ChartView.swift
Labels: 💥버그, 🔮리뷰, 🔥Feature, 🔍수정, 🧿UI, 🐸Architecture, 🔧Refactor

#115 [D] 활동 상세 화면 맵킷 연동 & 마일스톤 띄우기 & 글수정페이지 초기설정
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Extensions/BoosterObservable.swift
  Booster/Booster/Models/MileStone.swift
  Booster/Booster/Storyboards/Feed.storyboard
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/Usecases/HomeUsecase.swift
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
  Booster/Booster/ViewControllers/Feed/FeedViewController.swift
  Booster/Booster/ViewControllers/Feed/ModifyFeedViewController.swift
  Booster/Booster/ViewControllers/Home/HomeViewController.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/ViewModels/Feed/FeedViewModel.swift
  Booster/Booster/ViewModels/Home/HomeViewModel.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
  Booster/Booster/Views/Tracking/PhotoAnnotationView.swift
Labels: 🔮리뷰, 🔥Feature, 🧿UI

#113 [A] rx로 비동기 처리 및 프로퍼티 바인딩 리팩토링
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Extensions/BoosterObservable.swift
  Booster/Booster/Usecases/HomeUsecase.swift
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/ViewControllers/Home/HomeViewController.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/ViewModels/Feed/FeedViewModel.swift
  Booster/Booster/ViewModels/Home/HomeViewModel.swift
  Booster/Booster/ViewModels/Statistic/StatisticsViewModel.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
Labels: 🔮리뷰, 🐸Architecture, 🔧Refactor

#116 [B,D,F] 개인 설정 화면, 트래킹 일부 오류, 피드 리스트 오류 일부 수정
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Storyboards/Tracking.storyboard
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/ViewControllers/Enroll/EnrollViewController.swift
Labels: 💥버그, 🔥Feature, 🔍수정, 🧿UI, 🐸Architecture, 🔧Refactor

#124 [Setting] 탭바 아이콘 추가
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/Contents.json
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/feed.imageset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/feed.imageset/feed.png
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/feed.imageset/feed@2x.png
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/home.imageset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/home.imageset/home.png
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/home.imageset/home@2x.png
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/mypage.imageset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/mypage.imageset/mypage.png
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/mypage.imageset/mypage@2x.png
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/statistics.imageset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/statistics.imageset/statistics.png
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/statistics.imageset/statistics@2x.png
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/tracking.imageset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/tracking.imageset/tracking.png
  Booster/Booster/Resources/Assets.xcassets/BoosterTapbarIcons/tracking.imageset/tracking@2x.png
  Booster/Booster/Storyboards/Feed.storyboard
  Booster/Booster/Storyboards/Home.storyboard
  Booster/Booster/Storyboards/Statistics.storyboard
  Booster/Booster/Storyboards/Tracking.storyboard
  Booster/Booster/Storyboards/User.storyboard
Labels: 🧿UI

#132 [E] 개인 설정 화면 버그 픽스
  Booster/Booster/Extensions/UIAlertController+Extention.swift
  Booster/Booster/Storyboards/User.storyboard
  Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
  Booster/Booster/ViewControllers/User/EditUserInfoViewController.swift
  Booster/Booster/ViewControllers/User/EraseAllDataViewController.swift
  Booster/Booster/ViewControllers/User/UserViewController.swift
  Booster/Booster/ViewModels/User/UserViewModel.swift
  Booster/Booster/Views/User/EditUserInfoTextField.swift
  Booster/Booster/Views/User/UserInfoHeaderView.swift
Labels: 💥버그, 🔮리뷰, 🔍수정, 🧿UI

#139 [B, F] Tracking progress 부분 Rx로 변경 & Feed 리스트 오류 수정
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Models/Milestone.swift
  Booster/Booster/Models/TrackingModel.swift
  Booster/Booster/Models/UserInfo.swift
  Booster/Booster/Repositories/CoreData/User+CoreDataProperties.swift
  Booster/Booster/Resources/Booster.xcdatamodeld/Booster.xcdatamodel/contents
  Booster/Booster/Services/HealthStoreManager.swift
  Booster/Booster/Storyboards/Tracking.storyboard
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/Usecases/EnrollUsecase.swift
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
  Booster/Booster/ViewControllers/MileStone/MilestonePhotoViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/ViewModels/Feed/FeedViewModel.swift
  Booster/Booster/ViewModels/MileStone/MileStonePhotoViewModel.swift
  Booster/Booster/ViewModels/MileStone/MilestonePhotoViewModel.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
  Booster/Booster/Views/Feed/FeedCell.swift
  Booster/Booster/Views/Tracking/TrackingMapView.swift
  Booster/Tracking+CoreDataProperties.swift
Labels: 💥버그, 🔮리뷰, 🔍수정, 🐸Architecture, 🔧Refactor

#133 [F-14] 개인 정보 저장 버튼 오류
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Models/Milestone.swift
  Booster/Booster/Models/TrackingModel.swift
  Booster/Booster/Models/UserInfo.swift
  Booster/Booster/Repositories/CoreData/User+CoreDataProperties.swift
  Booster/Booster/Resources/Booster.xcdatamodeld/Booster.xcdatamodel/contents
  Booster/Booster/Services/HealthStoreManager.swift
  Booster/Booster/Storyboards/Tracking.storyboard
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/Usecases/EnrollUsecase.swift
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/ViewControllers/Enroll/EnrollViewController.swift
  Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
  Booster/Booster/ViewControllers/MileStone/MilestonePhotoViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/ViewModels/Feed/FeedViewModel.swift
  Booster/Booster/ViewModels/MileStone/MileStonePhotoViewModel.swift
  Booster/Booster/ViewModels/MileStone/MilestonePhotoViewModel.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
  Booster/Booster/Views/Feed/FeedCell.swift
  Booster/Booster/Views/Tracking/TrackingMapView.swift
  Booster/Tracking+CoreDataProperties.swift
Labels: 🔮리뷰, 🔍수정

#122 [D] 피드 리스트 Rx 수정 및 리스트 불러오기 수정
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Models/Milestone.swift
  Booster/Booster/Models/TrackingModel.swift
  Booster/Booster/Models/UserInfo.swift
  Booster/Booster/Repositories/CoreData/User+CoreDataProperties.swift
  Booster/Booster/Repositories/CoreDataManager.swift
  Booster/Booster/Resources/Booster.xcdatamodeld/Booster.xcdatamodel/contents
  Booster/Booster/Services/HealthStoreManager.swift
  Booster/Booster/Storyboards/Tracking.storyboard
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/Usecases/EnrollUsecase.swift
  Booster/Booster/Usecases/FeedUseCase.swift
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/ViewControllers/Enroll/EnrollViewController.swift
  Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
  Booster/Booster/ViewControllers/Feed/FeedViewController.swift
  Booster/Booster/ViewControllers/MileStone/MilestonePhotoViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/ViewModels/Feed/FeedViewModel.swift
  Booster/Booster/ViewModels/MileStone/MileStonePhotoViewModel.swift
  Booster/Booster/ViewModels/MileStone/MilestonePhotoViewModel.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
  Booster/Booster/Views/Feed/FeedCell.swift
  Booster/Booster/Views/Tracking/TrackingMapView.swift
  Booster/Tracking+CoreDataProperties.swift
Labels: 🔮리뷰, 🔍수정, 🐸Architecture

#143 [C] 통계 탭 오류 수정
  Booster/Booster/Storyboards/Statistics.storyboard
  Booster/Booster/Usecases/StatisticsUsecase.swift
  Booster/Booster/ViewControllers/Statistic/StatisticsViewController.swift
  Booster/Booster/ViewModels/Statistic/StatisticsViewModel.swift
Labels: 💥버그, 🔮리뷰, 🔍수정, 🧿UI

#144 [E-91] 알림 설정 화면
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/AppDelegates/AppDelegate.swift
  Booster/Booster/Extensions/UIImage+Extension.swift
  Booster/Booster/Resources/Assets.xcassets/BoosterNotificationImage/Contents.json
  Booster/Booster/Resources/Assets.xcassets/BoosterNotificationImage/notificationOff.imageset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/BoosterNotificationImage/notificationOff.imageset/notificationOff.png
  Booster/Booster/Resources/Assets.xcassets/BoosterNotificationImage/notificationOff.imageset/notificationOff@2x.png
  Booster/Booster/Resources/Assets.xcassets/BoosterNotificationImage/notificationOff.imageset/notificationOff@3x.png
  Booster/Booster/Resources/Assets.xcassets/BoosterNotificationImage/notificationOn.imageset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/BoosterNotificationImage/notificationOn.imageset/notificationOn.png
  Booster/Booster/Resources/Assets.xcassets/BoosterNotificationImage/notificationOn.imageset/notificationOn@2x.png
  Booster/Booster/Resources/Assets.xcassets/BoosterNotificationImage/notificationOn.imageset/notificationOn@3x.png
  Booster/Booster/Storyboards/User.storyboard
  Booster/Booster/ViewControllers/User/NotificationSettingViewController.swift
  Booster/Booster/ViewControllers/User/UserViewController.swift
Labels: 🔮리뷰, 🔥Feature, 🧿UI

#146 [B] 트래킹 시작 후 바로 거리가 증가하는 현상
  Booster/Booster/Repositories/CoreDataManager.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingViewController.swift
  Booster/Booster/Views/Tracking/TrackingMapView.swift
Labels: 💥버그, 🔮리뷰, 🔥Feature, 🔍수정, 🧿UI

#149 [D] Detail Feed 전체 로직 수정 & Rx
  Booster/Booster/Models/TrackingModel.swift
  Booster/Booster/Repositories/CoreDataManager.swift
  Booster/Booster/Storyboards/Feed.storyboard
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
  Booster/Booster/ViewControllers/Home/HomeViewController.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/Views/Tracking/PhotoAnnotationView.swift
Labels: 🔮리뷰, 🔥Feature, 🔍수정, 🧿UI, 🐸Architecture, 🔧Refactor

#151 [C] stepStatistics Unit Test
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/StatisticsTests/StatisticsViewModelTests.swift
  Booster/StatisticsTests/StepStatisticsTests.swift
Labels: 🔮리뷰, 💣Test

#157 [마일스톤] Rx로의 리팩토링
  Booster/Booster/AppDelegates/AppDelegate.swift
  Booster/Booster/Extensions/UIImage+Extension.swift
  Booster/Booster/Usecases/EnrollUsecase.swift
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/Usecases/UserUsecase.swift
  Booster/Booster/ViewControllers/MileStone/MilestonePhotoViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
Labels: 🔮리뷰, 🔧Refactor

#155 [E] 개인 설정 화면 리팩토링
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Storyboards/User.storyboard
  Booster/Booster/Usecases/UserUsecase.swift
  Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
  Booster/Booster/ViewControllers/User/EditUserInfoViewController.swift
  Booster/Booster/ViewControllers/User/EraseAllDataViewController.swift
  Booster/Booster/ViewControllers/User/NotificationSettingViewController.swift
  Booster/Booster/ViewControllers/User/RemoveAllDataViewController.swift
  Booster/Booster/ViewControllers/User/UserViewController.swift
  Booster/Booster/ViewModels/User/GoalViewModel.swift
  Booster/Booster/ViewModels/User/NotificationSettingViewModel.swift
  Booster/Booster/ViewModels/User/UserViewModel.swift
  Booster/Booster/Views/User/UserInfoHeaderView.swift
Labels: 🔮리뷰, 🐸Architecture, 🔧Refactor

#160 [D] 공유하기 기능, 글 수정 기능 구현 완료
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Models/WritingRecord.swift
  Booster/Booster/Storyboards/Feed.storyboard
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/Usecases/ModifyFeedUsecase.swift
  Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
  Booster/Booster/ViewControllers/Feed/FeedViewController.swift
  Booster/Booster/ViewControllers/Feed/ModifyFeedViewController.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/ViewModels/Feed/ModifyFeedViewModel.swift
Labels: 🔮리뷰, 🔥Feature, 🔍수정

#164 [A, C, 공통] 리팩토링, HealthKitManager
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Models/HomeModel.swift
  Booster/Booster/Models/Statistics.swift
  Booster/Booster/Models/StepStatitstics.swift
  Booster/Booster/Services/HealthKitManager.swift
  Booster/Booster/Usecases/HomeUsecase.swift
  Booster/Booster/Usecases/StatisticsUsecase.swift
  Booster/Booster/Usecases/UserUsecase.swift
  Booster/Booster/ViewControllers/Home/HomeViewController.swift
  Booster/Booster/ViewControllers/Statistic/StatisticsViewController.swift
  Booster/Booster/ViewModels/Home/HomeViewModel.swift
  Booster/Booster/ViewModels/Statistic/StatisticsViewModel.swift
Labels: 🔮리뷰, 🔍수정, 🔧Refactor

#165 [B] 걸음수 오류
  Booster/Booster/Repositories/CoreDataManager.swift
  Booster/Booster/Usecases/UserUsecase.swift
  Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
Labels: 💥버그, 🔮리뷰, 🔍수정

#167 [B, D] 공통 MapView 부모, 자식 클래스 구현 및 로직 분리, 리팩토링
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Models/Coordinate.swift
  Booster/Booster/Models/TrackingModel.swift
  Booster/Booster/Storyboards/Feed.storyboard
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/Usecases/UserUsecase.swift
  Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
  Booster/Booster/Views/Feed/DetailFeedMapView.swift
  Booster/Booster/Views/Tracking/TrackingMapView.swift
  Booster/Booster/Views/Utils/BoosterMapView.swift
  Booster/Booster/Views/Utils/EmptyView.swift
Labels: 🔮리뷰, 🔥Feature, 🔍수정, 🧿UI, 🔧Refactor

#168 [E] 개인 설정 화면 수정 및 리팩토링
  Booster/Booster/Repositories/CoreDataManager.swift
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/Usecases/UserUsecase.swift
  Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
  Booster/Booster/ViewControllers/User/EditUserInfoViewController.swift
  Booster/Booster/ViewControllers/User/UserViewController.swift
  Booster/Booster/ViewModels/User/UserViewModel.swift
Labels: 🔮리뷰, 🔍수정, 🐸Architecture, 🔧Refactor

#169 [A] 홈뷰컨 리팩토링
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Models/HomeModel.swift
  Booster/Booster/Services/HealthKitManager.swift
  Booster/Booster/Storyboards/Home.storyboard
  Booster/Booster/Usecases/HomeUsecase.swift
  Booster/Booster/ViewControllers/Home/HomeViewController.swift
  Booster/Booster/ViewModels/Home/HomeViewModel.swift
  Booster/Booster/Views/Home/GradientLabel.swift
Labels: 🔮리뷰, 🔧Refactor

#171 [B] 트래킹 화면 버그 픽스 및 User 화면 자잘한 리팩토링
  Booster/Booster/Storyboards/User.storyboard
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
  Booster/Booster/ViewControllers/User/RemoveAllDataViewController.swift
  Booster/Booster/ViewControllers/User/UserViewController.swift
  Booster/Booster/ViewModels/User/GoalViewModel.swift
  Booster/Booster/ViewModels/User/UserViewModel.swift
  Booster/Booster/Views/Tracking/TrackingMapView.swift
  Booster/Booster/Views/User/MyInfoHeaderView.swift
  Booster/Booster/Views/User/UserInfoBaseCell.swift
  Booster/Booster/Views/User/UserInfoHeaderView.swift
Labels: 💥버그, 🔮리뷰

#172 [B, 마일스톤] 리팩토링
  Booster/Booster/Models/Coordinate.swift
  Booster/Booster/Models/Milestone.swift
  Booster/Booster/Models/TrackingModel.swift
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
  Booster/Booster/Views/Feed/DetailFeedMapView.swift
Labels: 💥버그, 🔮리뷰, 🐸Architecture, 🔧Refactor

#183 [B] 트래킹 리팩토링
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Storyboards/Tracking.storyboard
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/Views/Tracking/TrackingInfoView.swift
Labels: 🔮리뷰, 🧿UI, 🔧Refactor

#181 [D] 피드 emtpy view 터치할 때 앱 크래시
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Storyboards/Tracking.storyboard
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/Feed/FeedViewModel.swift
  Booster/Booster/Views/Tracking/TrackingInfoView.swift
Labels: 💥버그, 🔮리뷰, 🔍수정

#180 [F] 클립보드 copy/paste 문제
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Views/Enroll/EnrollWriteView.swift
  Booster/Booster/Views/Utils/EnrollTextField.swift
Labels: 💥버그, 🔮리뷰

#176 [B] 트래킹 권한 확인 및 트래킹 종료 재확인
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Storyboards/Tracking.storyboard
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewModels/Feed/FeedViewModel.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
  Booster/Booster/Views/Enroll/EnrollWriteView.swift
  Booster/Booster/Views/Tracking/TrackingInfoView.swift
  Booster/Booster/Views/Utils/EnrollTextField.swift
Labels: 💥버그, 🔮리뷰, 🔥Feature

#187 [A, C] 홈 버그 수정, 통계 리팩토링
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster.xcodeproj/xcshareddata/xcschemes/Booster.xcscheme
  Booster/Booster/Models/StepStatitstics.swift
  Booster/Booster/Services/HealthKitManager.swift
  Booster/Booster/Storyboards/Home.storyboard
  Booster/Booster/Storyboards/Statistics.storyboard
  Booster/Booster/Usecases/HomeUsecase.swift
  Booster/Booster/Usecases/StatisticsUsecase.swift
  Booster/Booster/ViewControllers/Home/HomeViewController.swift
  Booster/Booster/ViewControllers/Statistic/StatisticsViewController.swift
  Booster/Booster/ViewModels/Home/HomeViewModel.swift
  Booster/Booster/ViewModels/Statistic/StatisticsViewModel.swift
  Booster/Booster/Views/Statistic/ChartView.swift
  Booster/Booster/Views/Statistic/SelectionChartView.swift
  Booster/StatisticsTests/StatisticsViewModelTests.swift
Labels: 💥버그, 🔮리뷰, 🔧Refactor

#189 [E] 클립보드 copy/paste 문제
  Booster/Booster/Views/User/EditUserInfoTextField.swift
Labels: 💥버그, 🔮리뷰

#190 [#172, #171, #168] 리팩토링PR 피드백 반영
  Booster/Booster/Usecases/TrackingProgressUsecase.swift
  Booster/Booster/Usecases/UserUsecase.swift
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewControllers/User/ChangeGoalViewController.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
Labels: 🔮리뷰, 🔍수정, 🔧Refactor

#186 [A, D] DetailFeed 리팩토링 및 뷰 재사용 추가
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Extensions/UIView+Extension.swift
  Booster/Booster/Models/Coordinate.swift
  Booster/Booster/Storyboards/Feed.storyboard
  Booster/Booster/Storyboards/Home.storyboard
  Booster/Booster/Usecases/DetailFeedUsecase.swift
  Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
  Booster/Booster/ViewControllers/Home/HomeViewController.swift
  Booster/Booster/ViewModels/Feed/DetailFeedViewModel.swift
  Booster/Booster/Views/Feed/DetailFeedMapView.swift
  Booster/Booster/Views/Tracking/TrackingMapView.swift
  Booster/Booster/Views/Utils/BoosterMapView.swift
  Booster/Booster/Views/Utils/ThreeColumnRecordView.swift
Labels: 🔮리뷰, 🧿UI, 🔧Refactor

#191 [TEST] Coordinates, Milestones 테스트 추가
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster.xcodeproj/xcshareddata/xcschemes/Booster.xcscheme
  Booster/Booster/Models/Coordinate.swift
  Booster/Booster/Models/Milestone.swift
  Booster/Booster/ViewModels/Tracking/TrackingProgressViewModel.swift
  Booster/CoordinateTests/CoordinateTests.swift
  Booster/MilestoneTests/MilestoneTests.swift
Labels: 💣Test

#198 [공통] NWPathMonitor추가
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Extensions/NWPathMonitor+Extension.swift
  Booster/Booster/ViewControllers/Feed/DetailFeedViewController.swift
Labels: 🔮리뷰, 🔥Feature

#196 [A] iPhone SE 뷰 짤리는 버그 수정
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster.xcodeproj/xcshareddata/xcschemes/Booster.xcscheme
  Booster/Booster/Models/StepStatitstics.swift
  Booster/Booster/Storyboards/Home.storyboard
  Booster/Booster/Storyboards/Statistics.storyboard
  Booster/Booster/ViewControllers/Statistic/StatisticsViewController.swift
  Booster/Podfile
  Booster/Podfile.lock
  Booster/StatisticsTests/StatisticsViewModelTests.swift
  Booster/StatisticsTests/StepStatisticsTests.swift
Labels: 💥버그, 🧿UI

#200 [B] tracking reachability
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingViewController.swift
  Booster/Booster/Views/Tracking/TrackingInfoView.swift
Labels: 🔮리뷰, 🌐Networking

#201 [E] 멘토 피드백 반영
  Booster/Booster/ViewControllers/User/EditUserInfoViewController.swift
  Booster/Booster/ViewControllers/User/UserViewController.swift
  Booster/Booster/ViewModels/User/NotificationSettingViewModel.swift
  Booster/Booster/ViewModels/User/UserViewModel.swift
Labels: 🔮리뷰, 🔧Refactor

#202 [E] 푸시 알람
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/AppDelegates/AppDelegate.swift
  Booster/Booster/Services/BoosterUserNotification.swift
Labels: 🔮리뷰, 🔥Feature

#203 [D] detailFeed뷰 아이폰SE 대응 수정
  Booster/Booster/Storyboards/Feed.storyboard
Labels: 💥버그, 🔮리뷰, 🔍수정, 🧿UI

#207 [A] coredata에서 goal가져오기, viewWillAppear뷰업데이트, 알림 설정
  Booster/Booster/Usecases/HomeUsecase.swift
  Booster/Booster/ViewControllers/Home/HomeViewController.swift
  Booster/Booster/ViewModels/Home/HomeViewModel.swift
  Booster/Booster/Views/Home/GradientLabel.swift
Labels: 🔮리뷰, 🔥Feature

#211 [A] 홈 뷰모델 유즈케이스 유닛테스트
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster.xcodeproj/xcshareddata/xcschemes/Booster.xcscheme
  Booster/HomeTests/HomeUsecaseTests.swift
  Booster/HomeTests/HomeViewModelTests.swift
  Booster/Podfile
  Booster/Podfile.lock
  Booster/StatisticsTests/StatisticsModelTests.swift
  Booster/StatisticsTests/StatisticsViewModelTests.swift
Labels: 🔮리뷰, 💣Test, 🔧Refactor

#209 [공통] TabBarController에서 권한 받기로 구현
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster/Services/HealthKitManager.swift
  Booster/Booster/Storyboards/Base.lproj/Main.storyboard
  Booster/Booster/ViewControllers/BaseProtocol/BoosterTabBarViewController.swift
  Booster/Booster/ViewControllers/Home/HomeViewController.swift
  Booster/Booster/ViewModels/Base/BoosterTabBarViewModel.swift
Labels: 🔮리뷰, 🔥Feature, 🐸Architecture

#213 [B] 통계 데이터 없을때 엠티뷰, 토스트메세지 작업
  Booster/Booster/Extensions/UIImage+Extension.swift
  Booster/Booster/Extensions/UIView+Extension.swift
  Booster/Booster/Resources/Assets.xcassets/lock.imageset/Contents.json
  Booster/Booster/Resources/Assets.xcassets/lock.imageset/lock.pdf
  Booster/Booster/Storyboards/Statistics.storyboard
  Booster/Booster/ViewControllers/Statistic/StatisticsViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingViewController.swift
  Booster/Booster/Views/Utils/EmptyView.swift
Labels: 🔮리뷰, 🔥Feature, 🧿UI

#216 [B] 트래킹 오류
  Booster/Booster/ViewControllers/Tracking/TrackingProgressViewController.swift
  Booster/Booster/ViewControllers/Tracking/TrackingViewController.swift
Labels: 💥버그

#217 [E] User 유닛 테스트
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster.xcodeproj/xcshareddata/xcschemes/Booster.xcscheme
  Booster/Booster/Models/Coordinate.swift
  Booster/Booster/Models/Milestone.swift
  Booster/Booster/ViewControllers/User/NotificationSettingViewController.swift
  Booster/Booster/ViewModels/User/NotificationSettingViewModel.swift
  Booster/CoordinateTests/CoordinateTests.swift
  Booster/MilestoneTests/MilestoneTests.swift
  Booster/UserTests/NotificationSettingViewModelTests.swift
  Booster/UserTests/UserTests.swift
  Booster/UserTests/UserViewModelTests.swift
Labels: 🔮리뷰, 💣Test

#218 [D] Detail Feed View Model 유닛테스트
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster.xcodeproj/xcshareddata/xcschemes/Booster.xcscheme
  Booster/FeedTests/DetailFeedViewModelTests.swift
  Booster/FeedTests/FeedTests.swift
  Booster/Podfile
Labels: 🔮리뷰, 🔥Feature, 💣Test

#219 [test] feed-list & enroll 유닛테스트
  Booster/Booster.xcodeproj/project.pbxproj
  Booster/Booster.xcodeproj/xcshareddata/xcschemes/Booster.xcscheme
  Booster/EnrollTests/EnrollTests.swift
  Booster/FeedListTests/FeedListTests.swift
Labels: 💣Test
